### PR TITLE
Security best practices

### PR DESCRIPTION
**Pull request by dscrobonia**
This PR adds security information to the USDR documentation.

Specifically:
- adds requirement for "data inventory" documentation for each project so that all data collected is clearly documented
- adds example "data inventory" documentation
- adds notes about automated security testing and security design reviews
- minor reformat to Data and Software Guidelines
- adds Security Best Practices document for web application and cloud development

### CODE REVIEW

**Comment by lklots** [comment]
i was going to make more comments but I'm a bit confused on the purpose and use of the doc. it feels very aspirational but without teeth. like i don't know who is actually reading it, forking it, or doing anything with it. i like what you wrote and what's contained in it but from a security perspective i would want people to do two things:
1. if you have PI data please let #security know
2. ask #security for any help with securing things

**Comment by waldoj** [comment]
We created the document in the first couple of weeks of USDR, because people were asking for standards to adhere to in the work that they were doing. and we didn't have a consistent answer. The idea wasn't to have any kind of enforcement mechanism, but just to document best practices. We published them in GitHub for lack of any other reasonable place to keep them, where people would know to find them or be able to propose changes to them.

**Comment by dscrobonia** [comment]
My assumption was that when engineers and PMs get onboarded this information would be passed to them to understand how USDR engineering operates. I'm not sure what happens in practice, but I wanted to make sure to add relevant security information to these docs.

@lklots I do agree with your two points, but what would "securing things" mean? That's where I'm hoping the "Security Best Practices" would help.

In that document there are recommendations for frontend libraries, what parts of an application to 100% ask for help on (including crypto & authentication), and some service advice/links on how to build things securely.

**Comment by lklots** [comment]
@waldoj do we share this doc with volunteers? are folks reading it?

**Comment by waldoj** [comment]
I'm sorry, @lklots, I don't know — I'm too far removed from volunteers' work at this point, now that my work is confined to the governments team. (I had a wider scope when I joined in mid-March, back when everybody did All The Things.)

**Pull request merged**
